name: Create Archive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*docs/* .editorconfig .gitignore requirements.txt'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
